const CELL_SIZE = 20;
const CACHE_CANVAS_SIZE_THRESHOLD = 10;

const PREVIEW_IMAGE_WIDTH = 200;
const PREVIEW_IMAGE_HEIGHT = 200;

export { CELL_SIZE, CACHE_CANVAS_SIZE_THRESHOLD, PREVIEW_IMAGE_WIDTH, PREVIEW_IMAGE_HEIGHT };
