name: Vercel Preview Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches-ignore:
            - main

jobs:
    Deploy-Preview:
        runs-on: ubuntu-latest
        permissions:
            deployments: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: install node
              uses: actions/setup-node@v3
              with:
                  node-version: "18.*"
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: check types
              run: pnpm run typecheck
            - name: linter
              run: pnpm run lint
            - name: run tests
              run: pnpm test || echo "tests failed but will continue becuase it's a preview"
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              id: upload_artifacts
              run: |
                  PREVIEW_LINK_TEMP=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tail -n 1 | grep -o 'https://.*')
                    echo "PREVIEW_LINK=$PREVIEW_LINK_TEMP" >> "$GITHUB_ENV"
            - uses: chrnorm/deployment-action@v2
              name: CREATE GH DEPLOYMENT
              id: deployment
              with:
                  token: "${{ github.token }}"
                  environment-url: ${{ steps.upload_artifacts.outputs.PREVIEW_LINK}}
                  environment: preview
                  log-url: ${{ steps.upload_artifacts.outputs.PREVIEW_LINK}}

            - name: Update deployment status (success)
              if: success()
              uses: chrnorm/deployment-status@v2
              with:
                  token: "${{ github.token }}"
                  environment-url: ${{ steps.deployment.outputs.environment_url }}
                  deployment-id: ${{ steps.deployment.outputs.deployment_id }}
                  state: "success"

            - name: Update deployment status (failure)
              if: failure()
              uses: chrnorm/deployment-status@v2
              with:
                  token: "${{ github.token }}"
                  environment-url: ${{ steps.deployment.outputs.environment_url }}
                  deployment-id: ${{ steps.deployment.outputs.deployment_id }}
                  state: "failure"
