on: 
    push:
    pull_request:
        branches: [main]
jobs:
    valid:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: use pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 7
            - name: install node
                uses: actions/setup-node@v3
                with:
                    node-version: 'lts'
                    cache: 'pnpm'
            - name: Install dependencies
            run: pnpm install
            - name: check types
                run: pnpm run typecheck 
            - name: run tests
                run: pnpm test